/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mzh_SDCardList */

#ifndef _Included_com_mzh_SDCardList
#define _Included_com_mzh_SDCardList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mzh_SDCardList
 * Method:    getSecond
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_mzh_SDCardList_getSecond
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
