/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xunlei_cloud_extstorage_FileSearchManager */

#ifndef _Included_com_xunlei_cloud_extstorage_FileSearchManager
#define _Included_com_xunlei_cloud_extstorage_FileSearchManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xunlei_cloud_extstorage_FileSearchManager
 * Method:    getSecond
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_xunlei_cloud_extstorage_FileSearchManager_searchFiles
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
